[workspace]

resolver = "2"

default-members = ["contract"]
members = ["contract", "integration-tests", "model"]

[workspace.dependencies]
fake = "2.9.2"
rand = "0.8.5"
anyhow = "1.0.79"
tokio = "1.36"

nitka = "0.4.0"
nitka-proc = "0.4.0"

claim-model = { path = "model" }
sweat-model = { git = "https://github.com/sweatco/sweat-near", rev = "537ef7d0aa3bf58d87b77a1c9660b2d0299b6c00" }

near-workspaces = "0.10.0"
near-sdk = "5.1.0"
near-contract-standards = "5.1.0"
